Grace/nav
calblueprint/lavamae pull request #153
Opened 2017-04-05 02:21 UTC by gracesnoh

![image](https://cloud.githubusercontent.com/assets/8237984/24686969/dcd804ec-196b-11e7-961a-9bfe2c4d2671.png)

![image](https://cloud.githubusercontent.com/assets/8237984/24686986/f1d83c7c-196b-11e7-836f-bb6166f28e76.png)

2017-04-05 21:23 UTC, caseytakahashi commented
Some new requests from Kris & Leah:

1. On the landing page, can we make the nav bar stay blue over the map instead of translucent? 
![screen shot 2017-04-05 at 2 19 45 pm](https://cloud.githubusercontent.com/assets/10657390/24727463/f3dbd16a-1a0a-11e7-994b-bdd09ea2c8b7.png)

2. Also, they want to increase the amount that the 2nd section below the map peeks out from beneath. I think on other computer screen sizes, it doesn't show up (they can't see that it peeks out) so let's increase the size of the white beneath the map!

2017-04-05 21:25 UTC, caseytakahashi requested changes

2017-04-05 21:25 UTC, caseytakahashi commented on app/views/partials/_nav.html.erb
> -      <form class="discussion-search">
They still want to include search in the discussions page! just not have it in the nav bar - so I think the best spot is in the light blue section (make the light blue section a bit thicker and add in the search bar above where the tags are)

![screen shot 2017-04-05 at 2 24 25 pm](https://cloud.githubusercontent.com/assets/10657390/24727658/96e22152-1a0b-11e7-84ab-54f86b88a382.png)

2017-04-07 07:12 UTC, gracesnoh commented
## Blue Nav + More Second Section
![image](https://cloud.githubusercontent.com/assets/8237984/24789199/c5f61b12-1b26-11e7-9296-8a5e172ba490.png)

## Responsive Nav
![image](https://cloud.githubusercontent.com/assets/8237984/24789162/946bbe62-1b26-11e7-98b2-e3d8f2160d2c.png)
![image](https://cloud.githubusercontent.com/assets/8237984/24789172/a47053fe-1b26-11e7-959e-2b97abab33a8.png)
![image](https://cloud.githubusercontent.com/assets/8237984/24789179/b1522c14-1b26-11e7-93a5-ccfd8cac77d3.png)

2017-04-10 02:56 UTC, caseytakahashi commented
OOOH this looks so good and love the way you styled the nav bar when it's on mobile :) LGTM!

2017-04-10 02:56 UTC, caseytakahashi approved these changes

2017-04-10 02:56 UTC, merged